siteName: Discuit
siteDescription: A free and open-source community platform.
emailContact:
twitterURL:
discordURL:
githubURL: https://github.com/discuitnet/discuit
substackURL:

isDevelopment: true
hmacSecret: <insert-your-secret-here>
noLogToFile: false
csrfOff: false

addr: :8080
sessionCookieName: SID

# MariaDB configuration:
dbAddr: 127.0.0.1 # Required
dbUser: discuit # Required
dbPassword: discuit # Required
dbName: discuit # Required

# MeiliSearch configuration:
searchEnabled: false
searchEngine: meilisearch
meiliHost: http://127.0.0.1:7700
meiliKey: <insert-your-key-here>

# ReCAPTCHA or hCaptcha secret and site-key:
captchaSecret:
captchaSiteKey:
disableRateLimits: false

# TLS certificate key-pair paths:
certFile:
keyFile:

defaultFeedSort: hot
disableForumCreation: true
forumCreationReqPoints: 10
maxForumsPerUser: 10
imagesFolderPath: "images"
